# Generated by Django 5.0.3 on 2024-03-30 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cadastro_em',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 9, 44, 36, 641778)),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 9, 44, 36, 641778)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 9, 44, 36, 641778)),
        ),
    ]
